[project]
name = "terse-repo"
version = "0.1.0"
description = "A project for learning to use git and Github"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.16.0",
]
scripts = [
    "hello = hello:main",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
